models/Part.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "part".
 *
 * @property int $id
 * @property string $date_create
 * @property string $number
 * @property int $id_marka
 * @property int $id_sklad
 * @property int $id_partner
 * @property int $id_tu
 * @property string $date_out
 * @property int $id_status
 * @property string $comment
 *
 * @property Marka $marka
 * @property Partner $partner
 * @property Sklad $sklad
 * @property Status $status
 * @property PartPack[] $partPacks
 */
class Part extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'part';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_create', 'date_out'], 'safe'],
            [['number','id_marka', 'id_tu'], 'required'],
            [['id_marka', 'id_sklad', 'id_partner', 'id_tu', 'id_status'], 'integer'],
            //[['id_sklad', 'id_partner', 'id_status'], 'filter', 'filter' => 'intval'], // для getDirtyAttributes
            [['id_sklad', 'id_status'], 'filter', 'filter' => 'intval'], // для getDirtyAttributes
            [['number', 'comment'], 'string', 'max' => 255],
            [['number'], 'unique'],
            [['id_marka'], 'exist', 'skipOnError' => true, 'targetClass' => Marka::className(), 'targetAttribute' => ['id_marka' => 'id']],
            [['id_partner'], 'exist', 'skipOnError' => true, 'targetClass' => Partner::className(), 'targetAttribute' => ['id_partner' => 'id']],
            [['id_sklad'], 'exist', 'skipOnError' => true, 'targetClass' => Sklad::className(), 'targetAttribute' => ['id_sklad' => 'id']],
            [['id_status'], 'exist', 'skipOnError' => true, 'targetClass' => Status::className(), 'targetAttribute' => ['id_status' => 'id']],
            [['id_tu'], 'exist', 'skipOnError' => true, 'targetClass' => Tu::className(), 'targetAttribute' => ['id_tu' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date_create' => 'Дата и время регистрации',
            'number' => 'Номер партии',
            'id_marka' => 'Марка продукции',
            'id_sklad' => 'Склад',
            'id_partner' => 'Партнёр',
            'date_out' => 'Дата отгрузки',
            'id_status' => 'Статус',
            'id_tu' => 'ТУ',
            'comment' => 'Комментарий',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMarka()
    {
        return $this->hasOne(Marka::className(), ['id' => 'id_marka']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPartner()
    {
        return $this->hasOne(Partner::className(), ['id' => 'id_partner']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSklad()
    {
        return $this->hasOne(Sklad::className(), ['id' => 'id_sklad']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTu()
    {
        return $this->hasOne(Tu::className(), ['id' => 'id_tu']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(StatusPart::className(), ['id' => 'id_status']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPartPacks()
    {
        return $this->hasMany(PartPack::className(), ['id_part' => 'id']);
    }




    private function getPacksArrayByPart($id){

        // По id партии ищем все мешки в пакетах
        $id_packs_arr = Packinpart::find()
            ->select('id_pack')
            ->where(['id_part' => $id])
            ->asArray()
            ->all();

        // выбор всех id мешков которые в пакете в числовой массив id - $id_packs
        $id_packs = [];
        foreach ($id_packs_arr as $value){
            $id_packs[] = (int)$value['id_pack'];
        }

        return $id_packs;
    }




    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {

            // Получить id пакета
            // Получить массив id мешков в пакете
            // Получить доступ к мешкам
            // Массив мешков передать в updateAll для изменения склада

            $newSklad =  $this->getDirtyAttributes(['id_sklad']);

            if ( !empty($newSklad) ){ // id_sklad или 0, или пусто, или вообще не определена (НЕ)';
            // было изменение класса - изменить склад всех мешков
                $id_packs = $this->getPacksArrayByPart($this->id);
                Pack::updateAll(['id_sklad'=>$newSklad['id_sklad']], ['id'=>$id_packs]);
            }

            $newStatus =  $this->getDirtyAttributes(['id_status']);

            if ( !empty($newStatus) && ($newStatus['id_status'] == 5) ){ // id_status или 0, или пусто, или вообще не определена (НЕ)';
            // было изменение статуса реализовано - изменить статус всех мешков и удалить их со складов
                $id_packs = $this->getPacksArrayByPart($this->id);
                Pack::updateAll(['id_status'=> 7, 'id_sklad'=> ''], ['id'=>$id_packs]);
                $this->id_sklad = '';
            }

            return true;
        } else {
            return false;
        }

    }



    /**
     * @return $number
     */
    static function getNumber($id)
    {
        $liters = [
            '18' => '18',
            '19' => 'A',
            '20' => 'B',
            '21' => 'C',
            '22' => 'E',
            '23' => 'F',
            '24' => 'G',
            '25' => 'H',
            '26' => 'K',
            '27' => 'M',
            '28' => 'N',
            '29' => 'P',
            '30' => 'R',
            '31' => 'S',
            '32' => 'T',
            '33' => 'U',
            '34' => 'V',
            '35' => 'W',
            '36' => 'X',
            '37' => 'Y',
            '38' => 'Z'
        ];

        // получаем текущий год
        $year = substr((new \DateTime('now', new \DateTimeZone('Europe/Moscow')))->format('Y'), 2, 4);

        // получаем литеру соответствующую году
        if (array_key_exists($year, $liters)) {
            $liter = $liters[$year];
        } else {
            $liter = 'AA';
        }

        $number = Part::find()
            ->select(['number'])
            ->where(['id_marka' => $id])
            ->andWhere(['like', 'number', $liter])
            ->orderBy('number')
            ->asArray()
            ->all();


        $marka = Marka::findOne($id)->title;

        if ($number == null) {
            $number = 1;
        } else {
            $number = end($number)['number'];
            $number = substr($number, 0, 4) + 1;
        }

        if ($number != 1) {
            switch (strlen($number)) {
                case 1:
                    $number = '000'.$number;
                    break;
                case 2:
                    $number = '00'.$number;
                    break;
                case 3:
                    $number = '0'.$number;
                    break;
            }
            $number .= '/' . $liter. '/'.$marka;
        }else{
            $number = '0001/' . $liter. '/'.$marka;
        }

        return $number;
    }




}

models/Smena.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "smena".
 *
 * @property int $id
 * @property string $title
 *
 * @property Pack[] $packs
 * @property PackFalse[] $packFalses
 */
class Smena extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'smena';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'string', 'max' => 160],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Наименование смены',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPacks()
    {
        return $this->hasMany(Pack::className(), ['id_smena' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPackFalses()
    {
        return $this->hasMany(PackFalse::className(), ['id_smena' => 'id']);
    }
}

controllers/PackController.php
<?php

namespace app\controllers;

use yii\data\ActiveDataProvider;
use app\models\PackFalse;
use Yii;
use app\models\Pack;
use app\models\PackSearch;
use app\models\PackFalseSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * PackController implements the CRUD actions for Pack model.
 */
class PackController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'index'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'], //аутентифицированным пользователям доступ к действию logout разрешить
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pack models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PackSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pack model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pack model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pack();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pack model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pack model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pack model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pack the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pack::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }



    public function actionNumPack()
    {
        if(Yii::$app->request->isAjax)
        {
            $id = (int)Yii::$app->request->post('id');
            $result = Pack::getNumber($id);

            return $result;
        }
        return 0;
    }


//Обработки сменщики____________________________________________________________________________________________________
    public function actionSmena()
    {
        $searchModel = new PackSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('smena/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSmenaCreate()
    {
        $model = new Pack();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['smena']);
        }

        return $this->render('smena/create', [
            'model' => $model,
        ]);
    }

    public function actionSmenaUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['smena']);
        }

        return $this->render('smena/update', [
            'model' => $model,
        ]);
    }

    public function actionSmenaView($id)
    {
        return $this->render('smena/view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionSmenaDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['smena']);
    }







//Обработки кладовщики____________________________________________________________________________________________________
    public function actionKlad()
    {
        $searchModel = new PackSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('klad/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionKladUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['klad']);
        }

        return $this->render('klad/update', [
            'model' => $model,
        ]);
    }

    public function actionKladView($id)
    {
        return $this->render('klad/view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionKladDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['klad']);
    }


    public function actionChangeSklad()
    {
        if(Yii::$app->request->isAjax) {
            $result = Yii::$app->request->post();
            return Pack::changeSklad($result);
        }
        else{
            return 0;
        }
    }





//Обработки лаборатория____________________________________________________________________________________________________
    public function actionLab()
    {
        $searchModel = new PackSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('lab/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionLabUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['lab']);
        }

        return $this->render('lab/update', [
            'model' => $model,
            'labels'=> Pack::fhpLabelsErrors($model),
        ]);
    }

    public function actionLabView($id)
    {
        return $this->render('lab/view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionLabDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['lab']);
    }

    public function actionAll($id)
    {

        $searchModelLog = new PackFalseSearch();
        $dataProviderLog = $searchModelLog->search(Yii::$app->request->queryParams);

        $number = Pack::findOne($id)->number;

        $query = PackFalse::find()->where(['number' => $number]);

        $dataProviderLog -> query = $query;
        $dataProviderLog -> sort -> defaultOrder = [
            'date_modify' => SORT_DESC
        ];

        return $this->render('all', [
            'searchModelLog'  => $searchModelLog,
            'dataProviderLog' => $dataProviderLog,
            'model' => $this->findModel($id),
        ]);

    }

}

views/pack/smena/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datetime\DateTimePicker;
use yii\widgets\MaskedInput;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Pack */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pack-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'date_create')->textInput(array(
        'value' => (new \DateTime('now', new \DateTimeZone('Europe/Moscow')))->format('Y-m-d H:i:s'),
        'class'=>'form-control','readonly' => true));
    ?>

    <?= $form->field($model, 'date_modify')->hiddenInput(array(
        'value' => (new \DateTime('now', new \DateTimeZone('Europe/Moscow')))->format('Y-m-d H:i:s'),
        'class'=>'form-control','readonly' => true))->label(false);
    ?>


    <?= $form->field($model, 'id_marka')
        ->dropDownList(\app\models\Marka::find()
            ->select(['title','id'])
            ->indexBy('id')
            ->column(),
            [
                'prompt' => '',
                'onchange' => '$.post(
                                      "'.Url::toRoute('pack/num-pack').'",
                                      {id : $(this).val()},
                                      function(data){
                                          $(".pack-number").val(data)
                                      }
                                )'
            ]
        )
    ?>


    <?= $form->field($model, 'number')->textInput(array(
        'maxlength' => true,
        'readonly' => true,
        'value' => 'Выберите вначале марку...',
        'class'=>'form-control pack-number'));
    ?>


    <?= $form->field($model, 'id_status')->hiddenInput(array(
        'value' => Yii::$app->params['statusDefault'],
        'class'=>'form-control','readonly' => true))->label(false);
    ?>


    <?php

    /*
        if (strpos(Yii::$app->request->queryParams['r'], 'create') == false) {
            echo $form->field($model, 'id_status')->dropDownList(\app\models\Status::find()->select(['title','id'])->indexBy('id')->column() );
        }else{
            echo $form->field($model, 'id_status')->hiddenInput(array(
                'value' => Yii::$app->params['statusDefault'],
                'class'=>'form-control','readonly' => true))->label(false);
        }
*/
    ?>



    <?= $form->field($model, 'id_sklad')->hiddenInput(['value' => 1])->label(false); ?>

    <?= $form->field($model, 'id_tu')->dropDownList(\app\models\Tu::find()->select(['title','id'])->indexBy('id')->column(),
            [
                'prompt' => ''
            ]
        ) ?>

    <?= $form->field($model, 'id_smena')->dropDownList(\app\models\Smena::find()->select(['title','id'])->indexBy('id')->column() ) ?>

    <?= $form->field($model, 'comment')->textarea(['rows' => 2]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/pack/smena/_formupdate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datetime\DateTimePicker;
use yii\widgets\MaskedInput;


/* @var $this yii\web\View */
/* @var $model app\models\Pack */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pack-form">
    <strong class = "lab_update_status" style="background-color: <?= $model->status->color; ?>">Текущий статус: <?= $model->status->title; ?></strong><br><br>
    <?php $form = ActiveForm::begin(); ?>

    <div class="row">

        <div class="col-md-6">

            <?= $form->field($model, 'date_create')->textInput(array('class'=>'form-control',
                                     'readonly' => true));
            ?>

            <?= $form->field($model, 'date_modify')->textInput(array(
                'value' => (new \DateTime('now', new \DateTimeZone('Europe/Moscow')))->format('Y-m-d H:i:s'),
                'class'=>'form-control',
                'readonly' => true));
            ?>

            <?= $form->field($model, 'number')->textInput(array(
                    'readonly' => true,
                    'maxlength' => true,
                    'value' => $model->number,
                    'class'=>'form-control'));
            ?>

        </div>

        <div class="col-md-6">

            <? /* = $form->field($model, 'id_marka')->dropDownList(\app\models\Marka::find()->select(['title','id'])->indexBy('id')->column() ) */ ?>

            <?= $form->field($model, 'id_smena')->dropDownList(\app\models\Smena::find()->select(['title','id'])->indexBy('id')->column() ) ?>

            <div style = 'display:none' >
                <?= $form->field($model, 'id_status')->dropDownList(\app\models\Status::find()->select(['title','id'])->where(['id' => [5]])->indexBy('id')->column() ) ?>
            </div>


        </div>

    </div>

    <?= $form->field($model, 'comment')->textarea(['rows' => 2]) ?>

    <div class="form-group">
        <?= Html::submitButton('Подтвердить статус', ['class' => 'btn btn-success']) ?>
        <strong class = "lab_update_status lab_new_status">Новый статус: Переработан</strong>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/pack/smena/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Pack */

$this->title = 'Новый мешок';
$this->params['breadcrumbs'][] = ['label' => 'Мешки', 'url' => ['smena']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pack-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/pack/smena/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PackSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Мешки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pack-index">

    <div class="alert alert-success">
        <h1>СМЕНА</h1>
    </div>

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Новый мешок', ['smena-create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?  $dataColumns =
        [
            [
                'attribute' => 'date_create',
                'format' =>  ['date', 'yyyy.MM.dd H:m:s'],
                'options' => ['width' => '200']
            ],

            'number',

            [
                'attribute'=>'id_marka',
                'value'=>'marka.title',
                'filter' => Html::activeDropDownList($searchModel, 'id_marka',
                    ArrayHelper::map(\app\models\Marka::find()->asArray()->all(), 'id', 'title'),
                    ['class'=>'form-control', 'prompt' => '...']),
                'enableSorting' => true,
            ],
            [
                'attribute'=>'id_sklad',
                'value'=>'sklad.title',
                'filter' => Html::activeDropDownList($searchModel, 'id_sklad',
                    ArrayHelper::map(\app\models\Sklad::find()->asArray()->all(), 'id', 'title'),
                    ['class'=>'form-control', 'prompt' => '...']),
                'enableSorting' => true,
            ],
            [
                'attribute'=>'id_smena',
                'value'=>'smena.title',
                'filter' => Html::activeDropDownList($searchModel, 'id_smena',
                    ArrayHelper::map(\app\models\Smena::find()->asArray()->all(), 'id', 'title'),
                    ['class'=>'form-control', 'prompt' => '...']),
                'enableSorting' => true,
            ],

            [
                'attribute'=>'id_status',
                'value'=>'status.title',
                'filter' => Html::activeDropDownList($searchModel, 'id_status',
                    ArrayHelper::map(\app\models\Status::find()->asArray()->all(), 'id', 'title'),
                    ['class'=>'form-control', 'prompt' => '...']),
                'enableSorting' => true,
                'contentOptions' =>function ($model, $key, $index, $column) {
                    $clr = \app\models\Status::findOne($model->id_status)->color;
                    return ['style' => 'background-color:'.$clr];
                },
            ],

            'comment:ntext',

            [
            'class' => 'yii\grid\ActionColumn',
            'contentOptions' => ['style' => 'white-space: nowrap; text-align: center; letter-spacing: 0.1em; max-width: 7em;'],

                //'template' => '{view} {update} {delete} {all}',
                'template' => '{view} {update} {all}',

                'buttons' => [

                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                            'title' => 'Подробнее',
                        ]);
                    },

                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                            'title' => 'Редактировать',
                        ]);
                    },
/*
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>',
                            ['smena-delete', 'id' => $model->id], [
                                'data' => [
                                    'confirm' => 'Выдействительно хотите удалить данный продукт?',
                                    'method' => 'post',
                            ],
                        ]);
                    },
*/
                    'all' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-th-list"></span>', $url, [
                            'title' => 'История продукта',
                        ]);
                    },

                ],

                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'update') {
                        $url ='index.php?r=pack%2Fsmena-update&id='.$model->id;
                        return $url;
                    };

                    if ($action === 'view') {
                        $url ='index.php?r=pack%2Fsmena-view&id='.$model->id;
                        return $url;
                    };
/*
                    if ($action === 'delete') {
                        $url ='index.php?r=pack%2Fsmena-delete&id='.$model->id;
                        return $url;
                    };
*/
                    if ($action === 'all') {
                        $url ='index.php?r=pack%2Fall&id='.$model->id;
                        return $url;
                    };

                },

            ],
        ]
    ?>

    <?= GridView::widget([
        'dataProvider'=>$dataProvider,
        'rowOptions' => ['style' => 'background-color:white;'],
        'pjax'=>false,
        'responsive'=>true,
        'panel'=>['type'=>'primary'],

        'columns' => $dataColumns,

        'toolbar' =>  [
            '{export}',
            '{toggleData}'
        ],
        'exportConfig' => [
            GridView::EXCEL => ['label' => 'Сохранить в файл EXCEL'],
        ],
        'filterModel'=>$searchModel,
    ]); ?>

</div>

views/pack/smena/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Pack */

$this->title = 'Редактировать продукт: '.$model->number;
$this->params['breadcrumbs'][] = ['label' => 'Мешки', 'url' => ['smena']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pack-update">

    <h1><?= Html::encode($this->title) ?></h1>
    <h2><?= $model->tu->title; ?></h2><br>

    <?= $this->render('_formupdate', [
        'model' => $model,
    ]) ?>

</div>

views/pack/smena/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Pack */

$this->title = $model->number;
$this->params['breadcrumbs'][] = ['label' => 'Мешки', 'url' => ['smena']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pack-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['smena-update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Выдействительно хотите удалить данный продукт?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            'date_create',
            'date_modify',
            'number',

            [
                'attribute' => 'marka.title',
            ],

            [
                'attribute' => 'tu.title',
            ],

            [
                'attribute' => 'smena.title',
            ],

            [
                'attribute' => 'status.title',
            ],

            [
                'attribute' => 'sklad.title',
            ],

            'fhp_diam',
            'fhp_massdol',
            'fhp_nasyp',
            'fhp_massdolprokal',
            'fhp_udel_azot',
            'fhp_udel_argon',
            'fhp_mech',
            'fhp_istir',
            'comment:ntext',
        ],

    ]) ?>

</div>