controllers/PackController.php
<?php

namespace app\controllers;

use yii\data\ActiveDataProvider;
use app\models\PackFalse;
use Yii;
use app\models\Pack;
use app\models\PackSearch;
use app\models\PackFalseSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * PackController implements the CRUD actions for Pack model.
 */
class PackController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'index'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'], //аутентифицированным пользователям доступ к действию logout разрешить
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pack models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PackSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pack model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pack model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pack();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pack model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pack model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pack model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pack the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pack::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }



    public function actionNumPack()
    {
        if(Yii::$app->request->isAjax)
        {
            $id = (int)Yii::$app->request->post('id');
            $result = Pack::getNumber($id);

            return $result;
        }
        return 0;
    }


//Обработки сменщики____________________________________________________________________________________________________
    public function actionSmena()
    {
        $searchModel = new PackSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('smena/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSmenaCreate()
    {
        $model = new Pack();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['smena']);
        }

        return $this->render('smena/create', [
            'model' => $model,
        ]);
    }

    public function actionSmenaUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['smena']);
        }

        return $this->render('smena/update', [
            'model' => $model,
        ]);
    }

    public function actionSmenaView($id)
    {
        return $this->render('smena/view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionSmenaDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['smena']);
    }







//Обработки кладовщики____________________________________________________________________________________________________
    public function actionKlad()
    {
        $searchModel = new PackSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('klad/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionKladUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['klad']);
        }

        return $this->render('klad/update', [
            'model' => $model,
        ]);
    }

    public function actionKladView($id)
    {
        return $this->render('klad/view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionKladDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['klad']);
    }


    public function actionChangeSklad()
    {
        if(Yii::$app->request->isAjax) {
            $result = Yii::$app->request->post();
            return Pack::changeSklad($result);
        }
        else{
            return 0;
        }
    }





//Обработки лаборатория____________________________________________________________________________________________________
    public function actionLab()
    {
        $searchModel = new PackSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('lab/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionLabUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['lab']);
        }

        return $this->render('lab/update', [
            'model' => $model,
            'labels'=> Pack::fhpLabelsErrors($model),
        ]);
    }

    public function actionLabView($id)
    {
        return $this->render('lab/view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionLabDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['lab']);
    }

    public function actionAll($id)
    {

        $searchModelLog = new PackFalseSearch();
        $dataProviderLog = $searchModelLog->search(Yii::$app->request->queryParams);

        $number = Pack::findOne($id)->number;

        $query = PackFalse::find()->where(['number' => $number]);

        $dataProviderLog -> query = $query;
        $dataProviderLog -> sort -> defaultOrder = [
            'date_modify' => SORT_DESC
        ];

        return $this->render('all', [
            'searchModelLog'  => $searchModelLog,
            'dataProviderLog' => $dataProviderLog,
            'model' => $this->findModel($id),
        ]);

    }

}

views/pack/klad/_formupdate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Pack */
/* @var $form yii\widgets\ActiveForm */
?>
<strong class = "lab_update_status" style="background-color: <?= $model->status->color; ?>">Текущий статус: <?= $model->status->title; ?></strong><br><br>


<div class="pack-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">

        <div class="col-md-6">

            <?= $form->field($model, 'date_create')->textInput(array('class'=>'form-control',
                'readonly' => true));
            ?>

            <?= $form->field($model, 'date_modify')->textInput(array(
                'value' => (new \DateTime('now', new \DateTimeZone('Europe/Moscow')))->format('Y-m-d H:i:s'),
                'class'=>'form-control',
                'readonly' => true));
            ?>

            <?= $form->field($model, 'number')->textInput(array(
                    'readonly' => true,
                    'maxlength' => true,
                    'value' => $model->number,
                    'class'=>'form-control'));
            ?>

        </div>

        <div class="col-md-6">


            <?= $form->field($model, 'id_sklad')
                ->dropDownList(\app\models\Sklad::find()
                    ->select(['title','id'])
                    ->indexBy('id')
                    ->column(),
                    [
                        'onchange' => "
                                    $.ajax({
                                      type: 'POST',
                                      url : '".Url::toRoute('pack/change-sklad')."',
                                      cache: false,
                                      data : {value : $(this).val(), id_status : '".$model->status->id."'},
                                      success : function(data){                                                                           
                                           if (data != 0) {
                                                $('#pack-id_status').val(data);
                                                $('.lab_new_status span').html($('#pack-id_status option:selected').text());
                                           }
                                    }
                                })"
                    ]

                )
            ?>

            <div style = 'display:none' >
                <?= $form->field($model, 'id_status')->dropDownList(\app\models\Status::find()->select(['title','id'])->indexBy('id')->column()) ?>
            </div>

        </div>

    </div>

    <?= $form->field($model, 'comment')->textarea(['rows' => 2]) ?>



    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        <strong class = "lab_update_status lab_new_status">Новый статус: <span><?= $model->status->title;?></span></strong>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/pack/klad/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PackSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Мешки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pack-index">

    <div class="alert alert-warning">
        <h1>КЛАДОВЩИК</h1>
    </div>

    <h1><?= Html::encode($this->title) ?></h1>

    <?  $dataColumns =
        [
            [
                'attribute' => 'date_create',
                'format' =>  ['date', 'yyyy.MM.dd H:m:s'],
                'options' => ['width' => '200']
            ],

            'number',

            [
                'attribute'=>'id_marka',
                'value'=>'marka.title',
                'filter' => Html::activeDropDownList($searchModel, 'id_marka',
                    ArrayHelper::map(\app\models\Marka::find()->asArray()->all(), 'id', 'title'),
                    ['class'=>'form-control', 'prompt' => '...']),
                'enableSorting' => true,
            ],


            [
                'attribute'=>'id_sklad',
                'value'=>'sklad.title',
                'filter' => Html::activeDropDownList($searchModel, 'id_sklad',
                    ArrayHelper::map(\app\models\Sklad::find()->asArray()->all(), 'id', 'title'),
                    ['class'=>'form-control', 'prompt' => '...']),
                'enableSorting' => true,
            ],

            [
                'attribute'=>'id_status',
                'value'=>'status.title',
                'filter' => Html::activeDropDownList($searchModel, 'id_status',
                    ArrayHelper::map(\app\models\Status::find()->asArray()->all(), 'id', 'title'),
                    ['class'=>'form-control', 'prompt' => '...']),
                'contentOptions' =>function ($model, $key, $index, $column) {
                    $clr = \app\models\Status::findOne($model->id_status)->color;
                    return ['style' => 'background-color:'.$clr];
                },
                'enableSorting' => true,
            ],

            'comment:ntext',

            [
            'class' => 'yii\grid\ActionColumn',
            'contentOptions' => ['style' => 'white-space: nowrap; text-align: center; letter-spacing: 0.1em; max-width: 7em;'],

                'template' => '{view} {update} {all}',

                'buttons' => [

                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                            'title' => 'Подробнее',
                        ]);
                    },

                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                            'title' => 'Редактировать',
                        ]);
                    },

                    'all' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-th-list"></span>', $url, [
                            'title' => 'История продукта',
                        ]);
                    },

                ],

                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'update') {
                        $url ='index.php?r=pack%2Fklad-update&id='.$model->id;
                        return $url;
                    };

                    if ($action === 'view') {
                        $url ='index.php?r=pack%2Fklad-view&id='.$model->id;
                        return $url;
                    };

                    if ($action === 'all') {
                        $url ='index.php?r=pack%2Fall&id='.$model->id;
                        return $url;
                    };
                },

            ],
        ]
    ?>

    <?= GridView::widget([
        'dataProvider'=>$dataProvider,
        'rowOptions' => ['style' => 'background-color:white;'],
        'pjax'=>false,
        'responsive'=>true,
        'panel'=>['type'=>'primary'],

        'columns' => $dataColumns,

        'toolbar' =>  [
            '{export}',
            '{toggleData}'
        ],
        'exportConfig' => [
            GridView::EXCEL => ['label' => 'Сохранить в файл EXCEL'],
        ],
        'filterModel'=>$searchModel,
    ]); ?>


</div>

views/pack/klad/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Pack */

$this->title = 'Редактировать продукт: '.$model->number;
$this->params['breadcrumbs'][] = ['label' => 'Мешки', 'url' => ['klad']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pack-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formupdate', [
        'model' => $model,
    ]) ?>

</div>

views/pack/klad/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Pack */

$this->title = $model->number;
$this->params['breadcrumbs'][] = ['label' => 'Мешки', 'url' => ['klad']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pack-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            'date_create',
            'date_modify',
            'number',

            [
                'attribute' => 'marka.title',
            ],

            [
                'attribute' => 'tu.title',
            ],

            [
                'attribute' => 'smena.title',
            ],

            [
                'attribute' => 'status.title',
            ],

            [
                'attribute' => 'sklad.title',
            ],

            'fhp_diam',
            'fhp_massdol',
            'fhp_nasyp',
            'fhp_massdolprokal',
            'fhp_udel_azot',
            'fhp_udel_argon',
            'fhp_mech',
            'fhp_istir',
            'comment:ntext',
        ],

    ]) ?>

</div>