models/Packinpart.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "packinpart".
 *
 * @property int $id
 * @property int $id_part
 * @property int $id_pack
 *
 *
 * @property Pack $pack
 * @property Part $part
 * @property NumberPart $numberPart
 * @property NumberPack $numberPack
 * @property DataCreatedPack $dataCreatedPack
 *
 */
class Packinpart extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'packinpart';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_part', 'id_pack'], 'required'],
            [['id_part', 'id_pack'], 'integer'],
            [['id_pack'], 'exist', 'skipOnError' => true, 'targetClass' => Pack::className(), 'targetAttribute' => ['id_pack' => 'id']],
            [['id_part'], 'exist', 'skipOnError' => true, 'targetClass' => Part::className(), 'targetAttribute' => ['id_part' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_part' => 'ID Партии',
            'id_pack' => 'ID Мешка',
            'dataCreatedPack' => 'Дата производства продукта',
            'numberPack' => 'Номер мешка',
            'numberPart' => 'Номер партии'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPack()
    {
        return $this->hasOne(Pack::className(), ['id' => 'id_pack']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPart()
    {
        return $this->hasOne(Part::className(), ['id' => 'id_part']);
    }

    /**
     * @return string
     */
    public function getNumberPart()
    {

        return Part::findOne($this->id_part)->number;

    }


    /**
     * @return string
     */
    public function getNumberPack()
    {

        return Pack::findOne($this->id_pack)->number;

    }

    /**
     * @return string
     */
    public function getDataCreatedPack()
    {

        return Pack::findOne($this->id_pack)->date_create;

    }
}

controllers/PackinpartController.php
<?php

namespace app\controllers;

use app\models\PackSearch;
use app\models\Pack;
use app\models\PackFalse;
use app\models\Part;
use Yii;
use app\models\Packinpart;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PackinpartController implements the CRUD actions for Packinpart model.
 */
class PackinpartController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Packinpart models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Packinpart::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Packinpart model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Packinpart model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Packinpart();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Packinpart model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Packinpart model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $pack = Pack::findOne(Packinpart::findOne($id)->id_pack);

        $packFalse = (PackFalse::find()
            ->where(['number' => $pack->number])
            ->orderBy(['id'=>SORT_DESC])
            ->one());
        $pack->id_status = $packFalse->id_status;
        $pack->update();

        $this->findModel($id)->delete();

        if (!Yii::$app->request->isAjax) {
            return $this->redirect(['add']);
        }
    }


    /**
     * Adding an existing Part packs.
     * id part
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionAdd($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Packinpart::find()->where(['id_part' => $id]),
            'pagination' => false
        ]);

        $searchPackModel = new PackSearch();

        $dataProviderPacks = $searchPackModel->search(Yii::$app->request->queryParams);
        $dataProviderPacks->query
            ->andWhere(['id_status' => [2,3]])
            ->andWhere(['id_sklad' => [2,3]])
            ->andWhere(['id_tu' => Part::findOne($id)->id_tu])
            ->andWhere(['id_marka' => Part::findOne($id)->id_marka]);

        return $this->render('add', [
            'partNumber' => Part::findOne($id)->number, // в actionChange()
            'partID' => Part::findOne($id)->id, // в actionChange()
            'dataProvider' => $dataProvider,
            'searchPackModel' => $searchPackModel,
            'dataProviderPacks' => $dataProviderPacks,
        ]);

    }


    public function actionChange()
    {

        if (\Yii::$app->request->isAjax) {
            $data = Yii::$app->request->post('keys');
            $id_part = Yii::$app->request->post('id');

            Pack::updateAll(['id_status'=>6], ['id'=>$data]);

            foreach ($data as $value){
                $packinpart[] = [ $id_part, $value ];
            }

            Yii::$app->db->createCommand()
                ->batchInsert(Packinpart::tableName(), ['id_part', 'id_pack'], $packinpart)
                ->execute();

            return false;

        }

    }




    /**
     * Finds the Packinpart model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Packinpart the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Packinpart::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PartController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Part;
use app\models\Pack;
use app\models\Packinpart;
use app\models\PartSearch;
use app\models\PackSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
/**
 * PartController implements the CRUD actions for Part model.
 */
class PartController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
          return [
              'access' => [
                  'class' => AccessControl::className(),
                  'only' => ['logout', 'index'],
                  'rules' => [
                      [
                          'actions' => ['logout', 'index'],
                          'allow' => true,
                          'roles' => ['@'], //аутентифицированным пользователям доступ к действию logout разрешить
                      ],
                      [
                          'actions' => ['index'],
                          'allow' => false,
                          'roles' => ['?'],
                      ],
                  ],
              ],
              'verbs' => [
                  'class' => VerbFilter::className(),
                  'actions' => [
                      'delete' => ['POST'],
                  ],
              ],
          ];
      }



    /**
     * Lists all Part models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PartSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Part model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {

        $dataProvider = new ActiveDataProvider([
            'query' => Packinpart::find()->where(['id_part' => $id]),
            'pagination' => false
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'dataProvider' => $dataProvider,
        ]);

    }

    /**
     * Creates a new Part model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Part();

        $dataProvider = new ActiveDataProvider([
            'query' => Pack::find(),
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Updates an existing Part model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Part model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Part model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Part the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Part::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }



    public function actionNumPart()
    {
        //if(Yii::$app->request->isAjax)
        $id = (int)Yii::$app->request->post('id');
        $result = Part::getNumber($id);

        return $result;
    }





//Обработки склад____________________________________________________________________________________________________
    public function actionKlad()
    {
        $searchModel = new PartSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('klad/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionKladUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['klad']);
        }

        $dataProvider = new ActiveDataProvider([
            'query' => Packinpart::find()->where(['id_part' => $id]),
            'pagination' => false
        ]);

        return $this->render('klad/update', [
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }








//Обработки лаборатория____________________________________________________________________________________________________
    public function actionLab()
    {
        $searchModel = new PartSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider -> sort -> defaultOrder = [
            'date_create' => SORT_DESC
        ];

        return $this->render('lab/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


   public function actionLabCreate()
    {
        $model = new Part();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['lab']);
        }

        return $this->render('lab/create', [
            'model' => $model,
        ]);
    }

    public function actionLabUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['lab']);
        }

        $dataProvider = new ActiveDataProvider([
            'query' => Packinpart::find()->where(['id_part' => $id]),
            'pagination' => false
        ]);

        return $this->render('lab/update', [
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }

    public function actionLabView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Packinpart::find()->where(['id_part' => $id]),
            'pagination' => false
        ]);

        return $this->render('lab/view', [
            'model' => $this->findModel($id),
            'dataProvider' => $dataProvider,
        ]);
    }

}

views/packinpart/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Packinpart */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="packinpart-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_part')->textInput() ?>

    <?= $form->field($model, 'id_pack')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/packinpart/add.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Продукция в партии: ' . $partNumber;

$this->params['breadcrumbs'][] = ['label' => 'Партии', 'url' => ['/part/lab']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="packinpart-index">

        <div class="jumbotron jumbotron-fluid">
            <h3>Продукция в партии <?= $partNumber ?></h3>
        </div>


        <?php Pjax::begin(['id' => 'pjax-container-packinpart', 'enablePushState' => false])?>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                //'id_part',
                //'numberPart',

                'numberPack',
                'dataCreatedPack',

                [
                    'class'    => 'yii\grid\ActionColumn',
                    'template' => '{delete}',
                    'buttons'  => [
                        'delete' => function ($url) {
                            return Html::a(Yii::t('yii', 'Delete'), '#', [
                                'title' => Yii::t('yii', 'Delete'),
                                'aria-label' => Yii::t('yii', 'Delete'),
                                'onclick' => "
                                if (confirm('Удалить продукт из партии?')) {
                                
                                    $.ajax('$url', {
                                        type: 'POST'
                                    }).done(function(data) {
                                        //$.pjax.reload({container: '#pjax-container-packinpart'});
                                        
                                        var pjaxContainers = ['#pjax-container-packinpart', '#pjax-container-pack'];
                                        $.pjax.reload({container: pjaxContainers[0]});
                                        $.each(pjaxContainers , function(index, container) { 
                                             if (index+1 < pjaxContainers.length) {
                                                  $(container).one('pjax:end', function (xhr, options) {
                                                       $.pjax.reload({container: pjaxContainers[index+1]}) ;
                                                  });
                                             }
                                        });
                                        
                                    });
                                    
                                }
                                return false;
                            ",
                            ]);
                        },
                    ],
                ],


                [
                    'class' => 'yii\grid\ActionColumn',
                    'contentOptions' => ['style' => 'white-space: nowrap; text-align: center; letter-spacing: 0.1em; max-width: 7em;'],

                    'template' => '{view}',

                    'buttons' => [

                        'view' => function ($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                'title' => 'Подробнее',
                            ]);
                        },
                    ],

                    'urlCreator' => function ($action, $model, $key, $index) {
                        if ($action === 'view') {
                            $url ='index.php?r=pack%2Flab-view&id='.$model->id_pack;
                            return $url;
                        };
                    },

                ],








            ],

        ]); ?>
        <?php Pjax::end(); ?>

</div>





<div class="jumbotron jumbotron-fluid">
    <h3>Продукция для отбора</h3>

    <button id="addpack" type="button" class="btn btn-success">Добавить выбранные в партию</button>

</div>


<?php Pjax::begin(['id' => 'pjax-container-pack']) ?>
<?= GridView::widget([
    'id' => 'grid-pack',
    'dataProvider' => $dataProviderPacks,
    'filterModel' => $searchPackModel,

    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'date_create',
        'number',

        [
            'attribute'=>'id_status',
            'value'=>'status.title',
            'filter' => Html::activeDropDownList($searchPackModel, 'id_status',
                ArrayHelper::map(\app\models\Status::find()->where(['id' => [2,3]])->asArray()->all(), 'id', 'title'),
                ['class'=>'form-control', 'prompt' => '...']),
            'enableSorting' => true,
            'contentOptions' =>function ($modelPack, $key, $index, $column) {
                $clr = \app\models\Status::findOne($modelPack->id_status)->color;
                return ['style' => 'background-color:'.$clr];
            },
        ],
        [
            'class' => 'yii\grid\CheckboxColumn',
            'checkboxOptions' => function ($model, $key, $index, $column) {
                return ['value' => $model->id];
            }
        ],
    ],
]); ?>
<?php Pjax::end(); ?>


</div>



<?php
$js = <<<JS

    $("#addpack").on("click", function(){
        
        var keys = $('#grid-pack').yiiGridView('getSelectedRows');
        
        $.ajax({
            url: 'index.php?r=packinpart/change',
            type: 'POST',
            data: {keys : keys, id: $partID},
            success: function(res){
                //$('.jumbotron h2').text(res);
                var pjaxContainers = ['#pjax-container-packinpart', '#pjax-container-pack'];
                $.pjax.reload({container: pjaxContainers[0]});
                $.each(pjaxContainers , function(index, container) { 
                     if (index+1 < pjaxContainers.length) {
                          $(container).one('pjax:end', function (xhr, options) {
                               $.pjax.reload({container: pjaxContainers[index+1]}) ;
                          });
                     }
                });
        },
        error: function(){
            alert('Ничего не выбрано!');
        }
        });
        return false;
    });

JS;

$this->registerJs($js);
?>

views/packinpart/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Packinpart */

$this->title = 'Create Packinpart';
$this->params['breadcrumbs'][] = ['label' => 'Packinparts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="packinpart-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/packinpart/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Packinparts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="packinpart-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Packinpart', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'id_part',
            'id_pack',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/packinpart/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Packinpart */

$this->title = 'Update Packinpart: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Packinparts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="packinpart-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/packinpart/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Packinpart */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Packinparts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="packinpart-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'id_part',
            'id_pack',
        ],
    ]) ?>

</div>